// <auto-generated />
using E25ProjetEtendu.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace E25ProjetEtendu.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250430145603_SeedProduit")]
    partial class SeedProduit
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.15")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("E25ProjetEtendu.Models.Produit", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("Qty")
                        .HasColumnType("int");

                    b.Property<bool>("estActif")
                        .HasColumnType("bit");

                    b.Property<string>("nom")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("note")
                        .HasColumnType("int");

                    b.Property<int>("prix")
                        .HasColumnType("int");

                    b.Property<string>("valeurNutritive")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("id");

                    b.ToTable("produits");

                    b.HasData(
                        new
                        {
                            id = 1,
                            Image = "redbull.jpg",
                            Qty = 120,
                            estActif = true,
                            nom = "Red Bull",
                            note = 4,
                            prix = 3,
                            valeurNutritive = "Calories: 110, Sucres: 27g, Caféine: 80mg, Glucides: 28g, Protéines: 1g"
                        },
                        new
                        {
                            id = 2,
                            Image = "pogo.jpg",
                            Qty = 200,
                            estActif = true,
                            nom = "Pogo",
                            note = 3,
                            prix = 2,
                            valeurNutritive = "Calories: 190, Lipides: 9g, Glucides: 20g, Protéines: 6g, Sodium: 500mg"
                        },
                        new
                        {
                            id = 3,
                            Image = "eau.jpg",
                            Qty = 300,
                            estActif = true,
                            nom = "Bouteille d'eau",
                            note = 5,
                            prix = 1,
                            valeurNutritive = "Calories: 0, Lipides: 0g, Sucres: 0g, Sodium: 0mg"
                        },
                        new
                        {
                            id = 4,
                            Image = "chips.jpg",
                            Qty = 100,
                            estActif = true,
                            nom = "Chips Lay’s",
                            note = 4,
                            prix = 2,
                            valeurNutritive = "Calories: 160, Lipides: 10g, Glucides: 15g, Sucres: 1g, Sodium: 170mg"
                        },
                        new
                        {
                            id = 5,
                            Image = "nutella.jpg",
                            Qty = 80,
                            estActif = true,
                            nom = "Nutella",
                            note = 5,
                            prix = 5,
                            valeurNutritive = "Calories: 200, Lipides: 11g, Glucides: 22g, Sucres: 21g, Protéines: 2g"
                        },
                        new
                        {
                            id = 6,
                            Image = "activia.jpg",
                            Qty = 150,
                            estActif = true,
                            nom = "Yogourt Activia",
                            note = 4,
                            prix = 3,
                            valeurNutritive = "Calories: 100, Lipides: 2g, Glucides: 15g, Sucres: 12g, Protéines: 5g"
                        },
                        new
                        {
                            id = 7,
                            Image = "pizza.jpg",
                            Qty = 60,
                            estActif = true,
                            nom = "Pizza congelée",
                            note = 4,
                            prix = 6,
                            valeurNutritive = "Calories: 350, Lipides: 15g, Glucides: 40g, Sucres: 5g, Protéines: 12g"
                        },
                        new
                        {
                            id = 8,
                            Image = "granola.jpg",
                            Qty = 180,
                            estActif = true,
                            nom = "Barre de granola",
                            note = 4,
                            prix = 2,
                            valeurNutritive = "Calories: 190, Lipides: 7g, Glucides: 29g, Sucres: 11g, Protéines: 4g"
                        },
                        new
                        {
                            id = 9,
                            Image = "coca.jpg",
                            Qty = 220,
                            estActif = true,
                            nom = "Coca-Cola",
                            note = 3,
                            prix = 2,
                            valeurNutritive = "Calories: 140, Sucres: 39g, Glucides: 39g, Sodium: 45mg"
                        },
                        new
                        {
                            id = 10,
                            Image = "sandwich.jpg",
                            Qty = 75,
                            estActif = true,
                            nom = "Sandwich jambon-fromage",
                            note = 4,
                            prix = 4,
                            valeurNutritive = "Calories: 320, Lipides: 12g, Glucides: 30g, Protéines: 18g, Sodium: 780mg"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
