// <auto-generated />
using E25ProjetEtendu.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace E25ProjetEtendu.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.15")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("E25ProjetEtendu.Models.Produit", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<bool>("EstActif")
                        .HasColumnType("bit");

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("Note")
                        .HasColumnType("int");

                    b.Property<decimal>("Prix")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Qty")
                        .HasColumnType("int");

                    b.Property<string>("ValeurNutritive")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("id");

                    b.ToTable("produits");

                    b.HasData(
                        new
                        {
                            id = 1,
                            EstActif = true,
                            Image = "redbull.jpg",
                            Nom = "Red Bull",
                            Note = 4,
                            Prix = 3m,
                            Qty = 120,
                            ValeurNutritive = "Calories: 110, Sucres: 27g, Caféine: 80mg, Glucides: 28g, Protéines: 1g"
                        },
                        new
                        {
                            id = 2,
                            EstActif = true,
                            Image = "pogo.jpg",
                            Nom = "Pogo",
                            Note = 3,
                            Prix = 2m,
                            Qty = 200,
                            ValeurNutritive = "Calories: 190, Lipides: 9g, Glucides: 20g, Protéines: 6g, Sodium: 500mg"
                        },
                        new
                        {
                            id = 3,
                            EstActif = true,
                            Image = "eau.jpg",
                            Nom = "Bouteille d'eau",
                            Note = 5,
                            Prix = 1m,
                            Qty = 300,
                            ValeurNutritive = "Calories: 0, Lipides: 0g, Sucres: 0g, Sodium: 0mg"
                        },
                        new
                        {
                            id = 4,
                            EstActif = true,
                            Image = "chips.jpg",
                            Nom = "Chips Lay’s",
                            Note = 4,
                            Prix = 2m,
                            Qty = 100,
                            ValeurNutritive = "Calories: 160, Lipides: 10g, Glucides: 15g, Sucres: 1g, Sodium: 170mg"
                        },
                        new
                        {
                            id = 5,
                            EstActif = true,
                            Image = "nutella.jpg",
                            Nom = "Nutella",
                            Note = 5,
                            Prix = 5m,
                            Qty = 80,
                            ValeurNutritive = "Calories: 200, Lipides: 11g, Glucides: 22g, Sucres: 21g, Protéines: 2g"
                        },
                        new
                        {
                            id = 6,
                            EstActif = true,
                            Image = "activia.jpg",
                            Nom = "Yogourt Activia",
                            Note = 4,
                            Prix = 3m,
                            Qty = 150,
                            ValeurNutritive = "Calories: 100, Lipides: 2g, Glucides: 15g, Sucres: 12g, Protéines: 5g"
                        },
                        new
                        {
                            id = 7,
                            EstActif = true,
                            Image = "pizza.jpg",
                            Nom = "Pizza congelée",
                            Note = 4,
                            Prix = 6m,
                            Qty = 60,
                            ValeurNutritive = "Calories: 350, Lipides: 15g, Glucides: 40g, Sucres: 5g, Protéines: 12g"
                        },
                        new
                        {
                            id = 8,
                            EstActif = true,
                            Image = "granola.jpg",
                            Nom = "Barre de granola",
                            Note = 4,
                            Prix = 2m,
                            Qty = 180,
                            ValeurNutritive = "Calories: 190, Lipides: 7g, Glucides: 29g, Sucres: 11g, Protéines: 4g"
                        },
                        new
                        {
                            id = 9,
                            EstActif = true,
                            Image = "coca.jpg",
                            Nom = "Coca-Cola",
                            Note = 3,
                            Prix = 2m,
                            Qty = 220,
                            ValeurNutritive = "Calories: 140, Sucres: 39g, Glucides: 39g, Sodium: 45mg"
                        },
                        new
                        {
                            id = 10,
                            EstActif = true,
                            Image = "sandwich.jpg",
                            Nom = "Sandwich jambon-fromage",
                            Note = 4,
                            Prix = 4m,
                            Qty = 75,
                            ValeurNutritive = "Calories: 320, Lipides: 12g, Glucides: 30g, Protéines: 18g, Sodium: 780mg"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
